name: Test Lib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libstt
      run: |
        wget https://github.com/coqui-ai/STT/releases/download/v1.2.0/libstt.tflite.Linux.zip && sudo unzip libstt.tflite.Linux.zip -d /lib
    
    - name: Install latest stable Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
      
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
